### ISSUE TITLE
Create a target to define the spatial AOI

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#11]
Potentially either: 

- read in an external shapefile (this [one](https://www.state.nj.us/drbc/basin/map/GIS.html)?) and convert to an sf object, or 
- use HUC codes and `nhdplusTools` to build the DRB polygon within the pipeline. 
 
Based on our discussion on 2/23/2022, we may try to load an external shapefile first, since the pattern of querying and conducting a spatial union on NHDPlusv2 catchments is probably tangential to what we're trying to accomplish here.

**Comment by jread-usgs** [comment]
Wondering if you may want to get even simpler and have your spatial area of interest be simply a triangle polygon where you specify the `sf` coordinates in the target recipe. You could then have a small comment letting people know how to replace that particulate target with an `sf::st_read()` of an external or web-available file. 

I think the objective here is to create a reusable starting point for others to build scalable/configurable WQP queries in R/targets/dataRetrieval, and it might be easier for users to spin up and for us to maintain if it doesn't require you to download an external file (e.g., the shapefile in this case).

**Comment by padilla410** [comment]
This morning we discussed starting with a simple bounding box, but the sticking point was - how do we then narrow down to the area of interest after the initial query?

The plan here was to create a tile set using the DRB shapefile --> query all sites within the tile set to make sure we grab all sites --> clip locations to DRB using the shapefile.

I wonder if the solution here is a bit of text that says "Hey we did it this way because of XYZ but this alternative solution (just a bounding box) would also work"
