### ISSUE TITLE
Should we use space or time to generate targets branches?

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#19]
There are use cases for both, e.g. `lake-surface-temperature-prep` uses the spatial approach whereas `2wp-temp-observations` uses the temporal approach. I tend to think the spatial approach is more applicable here because we can branch over the grids defined in `p1_conus_grid_aoi` to conduct the data pull, and easily scale if we need to. However, many users might have a defined basin or spatial extent, and just want to update the data from time-to-time. Using the temporal approach would mean not having to re-pull data that's already been gathered before.

**Comment by lekoenig** [comment]
> So it is hard to know when to consider an older year "current".

Good point @jread-usgs, thanks! I've been leaning toward branching over space to build targets with the idea that our example pipeline could be scaled up or down depending on the use case. Jordan brings up another reason to potentially go that route, namely that it might not be safe to assume that older data is 'current'. @padilla410  and @lindsayplatt, any other thoughts to add here?

**Comment by lindsayplatt** [comment]
No, I think that is an excellent point about WQP. I am comfortable moving forward with space rather than time chunking. Like many of the issues/decisions we have been making along the way, this seems like the sort of decision-making that should end up documented somewhere in the README or with the targets. That way, people can be aware that there are different ways to chunk up the pulls and what sort of considerations we made when choosing to show space.

**Comment by padilla410** [comment]
Howdy all, catching up here. First,I agree with Lindsay and Jordan - let's branch over space for this example. It would also be reasonable to mention the other approach in the doc. This could provide an opportunity for "someone else" to develop an example for and write up the second approach in more detail.

It could be worth briefly documenting the "things you didn't do" under the "Discussions" tab. That could provide me an opportunity to develop additional small tasks for folks after we complete this example.
